import {SSEParser,AnswerGate,requestFor,messageFor,statusLabel,safeURL} from './core.mjs';
import {local,cacheReports} from './storage.mjs';
const $=id=>document.getElementById(id);
let reports=[],turns=[],controller=null,lastRequest=null,token=sessionStorage.getItem('elderhelp-token'),capabilities=null;
const notice=text=>{$('notice').textContent=text;};
const node=(tag,text,className)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;};
const button=(text,action)=>{const b=node('button',text,'secondary');b.type='button';b.onclick=action;return b;};
function accessState(){ $('access-state').textContent=token?'· session saved':'· invite required';$('access').open=!token; }
async function request(path,body,signal){
  const response=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined,signal});
  if(!response.ok){if(response.status===401){token=null;sessionStorage.removeItem('elderhelp-token');accessState();}throw new Error(messageFor(response.status,response.headers.get('Retry-After')));}
  return response;
}
async function capabilitiesRefresh(){try{capabilities=await (await request('/v2/capabilities')).json();if(!capabilities.generation_available)notice('Verified answers are temporarily unavailable. Use Search passages or browse saved reports.');else notice('Connected · Answers are displayed after their supporting evidence is checked.');}catch(e){notice(e.message);}}
function showTab(tab){for(const id of ['ask','reports','history'])$(id).hidden=id!==tab;document.querySelectorAll('[data-tab]').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(tab==='history')historyList();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('login').onsubmit=async e=>{e.preventDefault();try{const session=await (await request('/v2/demo/session',{invite_code:$('invite').value})).json();token=session.token;sessionStorage.setItem('elderhelp-token',token);$('invite').value='';accessState();await capabilitiesRefresh();await refreshReports();}catch(e){notice(e.message);}};
$('logout').onclick=()=>{controller?.abort();token=null;sessionStorage.removeItem('elderhelp-token');accessState();notice('Access token removed. Your local history remains available.');};
function citation(c){$('sheet-title').textContent=`Source ${c.id}`;const content=$('sheet-content');content.replaceChildren(node('h3',c.report_title),node('p',`${c.publisher} · Published ${c.publication_date || 'date unknown'}`),node('p',`PDF page ${c.page_number}${c.page_label?` · printed label ${c.page_label}`:''}`),node('blockquote',c.excerpt));const url=safeURL(c.source_url);if(url){const a=node('a','Open publisher source ↗');a.href=url;a.target='_blank';a.rel='noopener noreferrer';content.append(a);}content.append(node('p','This is a saved excerpt. Publisher access and report approval may change.','hint'));$('sheet').showModal();}
$('close-sheet').onclick=()=>$('sheet').close();
function answerContent(result,container){container.replaceChildren(node('span',statusLabel(result.status),'status'));for(const part of result.answer_markdown.split('\n\n')){const p=node('p');let offset=0;for(const match of part.matchAll(/(?<!\\)\[(S\d+)\]/g)){p.append(document.createTextNode(part.slice(offset,match.index)));const c=result.citations.find(c=>c.id===match[1]);if(c){const b=button(match[0],()=>citation(c));b.className='citation';b.setAttribute('aria-label',`Source ${c.id}: ${c.report_title}, page ${c.page_number}`);p.append(b);}else p.append(document.createTextNode(match[0]));offset=match.index+match[0].length;}p.append(document.createTextNode(part.slice(offset)));container.append(p);}if(result.missing_parts?.length)container.append(node('p',`Missing evidence: ${result.missing_parts.join('; ')}`));for(const c of result.citations)container.append(button(`[${c.id}] ${c.report_title} · page ${c.page_number}`,()=>citation(c)));container.hidden=false;}
function busy(value){$('question').disabled=value;['ask-button','search-button','new-question','report-filter','followup'].forEach(id=>$(id).disabled=value);$('cancel').hidden=!value;$('retry').hidden=true;}
async function ask(payload){if(controller)return;lastRequest=structuredClone(payload);const active=new AbortController();controller=active;busy(true);$('answer').hidden=true;$('search-results').replaceChildren();$('progress').textContent='Connecting… A sleeping host may take a moment to wake.';const timeout=setTimeout(()=>active.abort('timeout'),90000);try{const response=await request('/v2/answers/stream',payload,active.signal);const reader=response.body.getReader();const decoder=new TextDecoder();const parser=new SSEParser();const gate=new AnswerGate();let result=null;try{while(true){const {value,done}=await reader.read();if(done)break;for(const event of parser.feed(decoder.decode(value,{stream:true}))){if(event.name==='progress')$('progress').textContent=event.data.message;const complete=gate.accept(event);if(complete)result=complete;}}}finally{reader.releaseLock();}if(!gate.done || !result)throw new Error('The connection ended before verification completed. Retry the question.');if(active.signal.aborted)throw new DOMException('Aborted','AbortError');answerContent(result,$('answer'));turns=[...payload.history,{role:'user',content:payload.question},{role:'assistant',content:result.answer_markdown.slice(0,8000)}].slice(-6);try{await local('history','put',{id:result.request_id,created:Date.now(),question:payload.question,result});$('progress').textContent='Verification complete · Saved on this browser.';}catch{$('progress').textContent='Verification complete. Browser storage is unavailable, so this answer was not saved.';}}catch(e){notice(active.signal.aborted?(active.signal.reason==='timeout'?'The host did not finish in time. It may be waking up. Retry explicitly.':'Answer stopped. Nothing was saved.'):e.message);$('progress').textContent='';$('retry').hidden=false;}finally{clearTimeout(timeout);controller=null;const retry=!$('retry').hidden;busy(false);$('retry').hidden=!retry;}}
$('question-form').onsubmit=e=>{e.preventDefault();const q=$('question').value.trim();if(q && q.length<=2000)ask(requestFor(q,turns,$('followup').checked,$('report-filter').value));};
$('retry').onclick=()=>lastRequest&&ask(lastRequest);
$('cancel').onclick=()=>controller?.abort();
$('new-question').onclick=()=>{turns=[];lastRequest=null;$('question').value='';$('followup').checked=false;$('answer').hidden=true;$('search-results').replaceChildren();$('progress').textContent='';$('retry').hidden=true;$('question').focus();};
$('search-button').onclick=async()=>{const q=$('question').value.trim();if(!q)return;const active=new AbortController();controller=active;busy(true);$('progress').textContent='Searching approved passages…';try{const value=await(await request('/v2/search',{...requestFor(q,[],false,$('report-filter').value),mode:'keyword'},active.signal)).json();const list=$('search-results');list.replaceChildren(node('h2','Matching passages'));if(!value.items.length)list.append(node('p','No matching approved passages. Try fewer keywords.'));for(const hit of value.items){const item=node('article');item.append(node('h3',hit.citation.report_title),node('p',hit.citation.excerpt),button(`Inspect page ${hit.citation.page_number}`,()=>citation(hit.citation)));list.append(item);}$('progress').textContent='Keyword results · No generated answer.';}catch(e){notice(active.signal.aborted?'Search stopped.':e.message);$('progress').textContent='';}finally{controller=null;busy(false);}};
function reportList(){const list=$('report-list');list.replaceChildren();const query=$('library-query').value.toLowerCase();for(const r of reports.filter(r=>`${r.title} ${r.publisher} ${r.community}`.toLowerCase().includes(query))){const item=node('article',undefined,'card');item.append(node('h3',r.title),node('p',`${r.publisher} · ${r.community}`,'hint'),node('p',`Published ${r.publication_date || 'date unknown'}`),button('Ask about this report',()=>{$('report-filter').value=r.id;showTab('ask');}),button('Report details',()=>reportDetail(r)));list.append(item);}if(!list.children.length)list.append(node('p','No matching saved reports. Connect with an invite code and refresh.'));}
async function reportDetail(r){$('sheet-title').textContent=r.title;const content=$('sheet-content');content.replaceChildren(node('p',`${r.publisher} · ${r.community} · ${r.publication_date||'date unknown'}`));const link=safeURL(r.source_url);if(link){const a=node('a','Open publisher source ↗');a.href=link;a.target='_blank';a.rel='noopener noreferrer';content.append(a);}$('sheet').showModal();try{const d=await(await request(`/v2/reports/${r.id}`)).json();content.append(node('p',d.description||''),node('h3','Questions to explore'));for(const q of d.suggested_questions)content.append(button(q,()=>{$('sheet').close();$('question').value=q;$('report-filter').value=r.id;showTab('ask');}));}catch{content.append(node('p','Showing saved metadata; detailed information is unavailable.'));}}
async function refreshReports(){try{let fresh=[],offset=0;while(true){const page=await(await request(`/v2/reports?offset=${offset}&limit=100`)).json();fresh.push(...page.items);offset+=page.items.length;if(offset>=page.total || !page.items.length)break;}reports=fresh;await cacheReports(reports);renderReports();}catch(e){notice(`${e.message} Showing saved report metadata.`);}}
function renderReports(){const selected=$('report-filter').value;$('report-filter').replaceChildren(new Option('All approved reports',''));reports.forEach(r=>$('report-filter').append(new Option(r.title,r.id)));$('report-filter').value=selected;reportList();}
$('refresh').onclick=refreshReports;$('library-query').oninput=reportList;
async function historyList(){const list=$('history-list');try{const rows=await local('history','getAll');list.replaceChildren();for(const row of rows.sort((a,b)=>b.created-a.created)){const item=node('article',undefined,'card');item.append(node('h3',row.question),node('p',new Date(row.created).toLocaleString(),'hint'),button('Read saved answer',()=>{$('sheet-title').textContent=row.question;answerContent(row.result,$('sheet-content'));$('sheet').showModal();}),button('Delete conversation',async()=>{await local('history','delete',row.id);historyList();}));list.append(item);}if(!rows.length)list.append(node('p','No saved answers yet. Completed answers will appear here.'));}catch{notice('Local browser storage is unavailable.');}}
$('clear-history').onclick=async()=>{if(confirm('Delete all completed answers from this browser?')){await local('history','clear');turns=[];historyList();}};
window.addEventListener('offline',()=>notice('You are offline. Saved report metadata and history are still available.'));
accessState();try{reports=await local('reports','getAll');renderReports();}catch{notice('Local browser storage is unavailable.');}if(token){await capabilitiesRefresh();await refreshReports();}
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
