// Generated by tools/generate_models.py from ../openapi.json. Do not edit.
package com.adityaice.elderhelp

import kotlinx.serialization.Serializable

@Serializable
data class ReportSummary(
    val id: String,
    val slug: String,
    val title: String,
    val publisher: String,
    val community: String,
    val publication_date: String? = null,
    val source_url: String,
)

@Serializable
data class ReportDetail(
    val id: String,
    val slug: String,
    val title: String,
    val publisher: String,
    val community: String,
    val publication_date: String? = null,
    val source_url: String,
    val description: String? = null,
    val suggested_questions: List<String> = emptyList(),
    val page_count: Int,
)

@Serializable
data class ReportList(
    val items: List<ReportSummary>,
    val total: Int,
)

@Serializable
data class ChatTurn(
    val role: String,
    val content: String,
)

@Serializable
data class AnswerFilters(
    val report_ids: List<String> = emptyList(),
    val community: String? = null,
    val year_from: Int? = null,
    val year_to: Int? = null,
)

@Serializable
data class AnswerRequest(
    val question: String,
    val history: List<ChatTurn> = emptyList(),
    val filters: AnswerFilters = AnswerFilters(),
)

@Serializable
data class Citation(
    val id: String,
    val report_id: String,
    val report_title: String,
    val publisher: String,
    val source_url: String,
    val publication_date: String? = null,
    val page_number: Int,
    val excerpt: String,
)

@Serializable
data class AnswerComplete(
    val request_id: String,
    val answer_markdown: String,
    val status: String,
    val citations: List<Citation>,
)
