"""Generate Kotlin DTOs from the committed OpenAPI schemas; no hand-maintained DTOs."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
schemas = json.loads((root / 'openapi.json').read_text())['components']['schemas']
names = ['ReportSummary', 'ReportDetail', 'ReportList', 'ChatTurn', 'AnswerFilters', 'AnswerRequest', 'Citation', 'AnswerComplete']

def kind(s):
    if '$ref' in s:
        return s['$ref'].split('/')[-1]
    if 'anyOf' in s:
        return kind(next(x for x in s['anyOf'] if x.get('type') != 'null')) + '?'
    return {'string': 'String', 'integer': 'Int', 'boolean': 'Boolean', 'array': lambda: 'List<' + kind(s['items']) + '>'}[s['type']]() if s['type'] == 'array' else {'string': 'String', 'integer': 'Int', 'boolean': 'Boolean'}[s['type']]

out = ['// Generated by tools/generate_models.py from ../openapi.json. Do not edit.', 'package com.adityaice.elderhelp', '', 'import kotlinx.serialization.Serializable', '']
for name in names:
    s = schemas[name]
    out += ['@Serializable', f'data class {name}(']
    for field, prop in s['properties'].items():
        t = kind(prop)
        default = ''
        if field not in s.get('required', []):
            default = ' = null' if t.endswith('?') else (' = emptyList()' if t.startswith('List<') else ' = ' + t + '()')
        out += [f'    val {field}: {t}{default},']
    out += [')', '']
(root / 'android/app/src/main/java/com/adityaice/elderhelp/Models.kt').write_text('\n'.join(out))
