"""Generate Kotlin DTOs from the committed OpenAPI schemas; no hand-maintained DTOs."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
schemas = json.loads((root / 'openapi.json').read_text())['components']['schemas']
names = {'ReportSummary':'ReportSummaryV2', 'ReportDetail':'ReportDetailV2', 'ReportList':'ReportListV2', 'ChatTurn':'ChatTurn', 'AnswerFilters':'AnswerFilters', 'AnswerRequest':'AnswerRequest', 'Citation':'CitationV2', 'AnswerComplete':'CompleteV2', 'PilotSession':'SessionResponse', 'Capabilities':'Capabilities', 'SearchHit':'SearchHit', 'SearchResponse':'SearchResponse', 'SessionRequest':'SessionRequest'}
aliases = {v:k for k,v in names.items()}
# Added v2 provenance is optional only for restoring older local v1 history.
# The network layer requires these fields on v2 completions.
legacy_optional = {'revision_id', 'span_id', 'acquired_at'}

def kind(s):
    if '$ref' in s:
        name = s['$ref'].split('/')[-1]
        return aliases.get(name, name)
    if 'anyOf' in s:
        return kind(next(x for x in s['anyOf'] if x.get('type') != 'null')) + '?'
    if s['type'] == 'array':
        return 'List<' + kind(s['items']) + '>'
    return {'string': 'String', 'integer': 'Int', 'boolean': 'Boolean', 'number': 'Double'}[s['type']]


out = ['// Generated by tools/generate_models.py from ../openapi.json. Do not edit.', 'package com.adityaice.elderhelp', '', 'import kotlinx.serialization.Serializable', '']
for name, schema_name in names.items():
    s = schemas[schema_name]
    out += ['@Serializable', f'data class {name}(']
    for field, prop in s['properties'].items():
        t = kind(prop)
        default = ''
        if field in legacy_optional and not t.endswith('?'):
            t += '?'
        if field in legacy_optional:
            default = ' = null'
        if field not in s.get('required', []):
            if 'default' in prop and not isinstance(prop['default'], (dict, list)):
                default = ' = ' + json.dumps(prop['default'])
            else:
                default = ' = null' if t.endswith('?') else (' = emptyList()' if t.startswith('List<') else ' = ' + t + '()')
        out += [f'    val {field}: {t}{default},']
    out += [')', '']
(root / 'android/app/src/main/java/com/adityaice/elderhelp/Models.kt').write_text('\n'.join(out))
